#ifndef LCP_PIVOT
#define LCP_PIVOT

#define LCP_PIVOT_SUCCESS 0
#define LCP_PIVOT_NUL 2
#define LCP_PATHSEARCH_LEAVING_T 3
#define LCP_PIVOT_RAY_TERMINATION 4
#define LCP_PATHSEARCH_NON_ENTERING_T 5
#define LCP_PIVOT_LUMOD_FAILED 6

#endif
